const riskFactors = ["Taiwan semiconductor exposure","China manufacturing exposure","Advanced packaging exposure","HBM/memory exposure","Battery minerals exposure","Rare earth exposure","Data-center power exposure","Logistics chokepoint exposure","Single-supplier concentration","Export control exposure","Energy sensitivity","Inventory buffer weakness"];

const companies = [
{ticker:"AAPL",name:"Apple",sector:"Consumer Tech",segments:["iPhone","Mac","Services"],products:["iPhone","Mac","iPad","Apple Silicon"],suppliers:["TSMC","Foxconn","Pegatron","Luxshare","Samsung"],materials:["Silicon wafers","Copper","Rare earth magnets","Batteries","Cobalt","Lithium","Gold"],regions:["Taiwan","China","India","Vietnam"],riskScores:[88,85,72,64,58,66,42,69,74,61,39,55],resilienceScore:63,mainRiskNarrative:"Apple couples premium demand with concentrated Asian hardware chains and deep TSMC dependency.",strategicImplication:"Diversification to India/Vietnam reduces but does not remove concentration risk."},
{ticker:"MSFT",name:"Microsoft",sector:"Cloud & Software",segments:["Azure","Office","AI"],products:["Azure AI","Data centers","Surface"],suppliers:["Nvidia","TSMC","SK Hynix","Dell","Supermicro","Schneider Electric"],materials:["HBM memory","DRAM","Copper","Transformers","Cooling systems","Data-center power equipment"],regions:["US","Taiwan","South Korea","EU"],riskScores:[73,32,68,81,22,28,86,48,59,72,84,52],resilienceScore:71,mainRiskNarrative:"AI-scale cloud turns software economics into physical infrastructure economics.",strategicImplication:"Grid access and supplier portfolio breadth define AI growth velocity."},
{ticker:"NVDA",name:"Nvidia",sector:"Semiconductors",segments:["Data center","Gaming","Automotive"],products:["AI GPUs","Networking","Grace CPUs"],suppliers:["TSMC","SK Hynix","Samsung","Micron","ASE","Amkor"],materials:["Silicon wafers","HBM memory","Neon gas","Photoresists","Advanced substrates","Copper","Gold"],regions:["Taiwan","South Korea","US","Malaysia"],riskScores:[96,28,94,97,20,24,67,63,82,88,58,62],resilienceScore:56,mainRiskNarrative:"Nvidia’s bottleneck is concentrated advanced manufacturing capacity, not demand.",strategicImplication:"Packaging and HBM are strategic constraints on AI deployment."},
{ticker:"AMZN",name:"Amazon",sector:"E-commerce & Cloud",segments:["AWS","Retail","Logistics"],products:["AWS AI","Fulfillment","Kuiper"],suppliers:["Nvidia","TSMC","Arista","Vertiv","Maersk","UPS"],materials:["HBM memory","Copper","Fiber optic components","Cooling systems","Data-center power equipment"],regions:["US","China","Taiwan","Global shipping lanes"],riskScores:[69,54,62,79,21,24,88,77,55,66,87,49],resilienceScore:68,mainRiskNarrative:"Amazon has dual exposure: hyperscale compute buildout and global logistics frictions.",strategicImplication:"Shipping plus power constraints can simultaneously pressure margins and growth."},
{ticker:"GOOGL",name:"Alphabet",sector:"Internet & Cloud",segments:["Google Cloud","Ads","Devices"],products:["TPUs","AI cloud","Pixel"],suppliers:["TSMC","Nvidia","Broadcom","SK Hynix","Corning"],materials:["Silicon wafers","HBM memory","DRAM","Copper","Power semiconductors"],regions:["US","Taiwan","Korea"],riskScores:[74,40,66,78,24,22,85,45,57,70,82,50],resilienceScore:72,mainRiskNarrative:"Alphabet’s AI strategy depends on chip foundry concentration and power-intensive scaling.",strategicImplication:"Chip optionality and regional power procurement are key moats."},
{ticker:"META",name:"Meta",sector:"Social & AI",segments:["Family of apps","Reality Labs","AI infra"],products:["AI clusters","Recommenders","XR devices"],suppliers:["Nvidia","TSMC","Supermicro","Arista","Vertiv"],materials:["HBM memory","Copper","Cooling systems","Data-center power equipment","Rare earth magnets"],regions:["US","Taiwan","Korea"],riskScores:[72,34,63,82,19,27,89,41,53,68,86,48],resilienceScore:69,mainRiskNarrative:"Meta’s AI ambitions convert into heavy dependence on GPU-memory-power stacks.",strategicImplication:"Execution risk shifts from software talent to physical capacity access."},
{ticker:"TSLA",name:"Tesla",sector:"EV & Energy",segments:["EVs","Energy storage","Autonomy"],products:["Model lineup","Megapack","Dojo"],suppliers:["Panasonic","CATL","LG Energy Solution","BYD","TSMC"],materials:["Lithium","Nickel","Cobalt","Graphite","Copper","Aluminum","Power semiconductors"],regions:["US","China","Germany"],riskScores:[52,71,49,44,93,61,59,64,58,47,66,57],resilienceScore:65,mainRiskNarrative:"Tesla’s main chain is mineral-to-battery-to-power-electronics with policy-sensitive footprint.",strategicImplication:"Vertical integration helps, but battery mineral cycles remain a structural risk."}
];

const materials = ["Silicon wafers","Copper","Aluminum","Lithium","Nickel","Cobalt","Graphite","Rare earth magnets","Gallium","Germanium","Tantalum","Tin","Gold","Silver","Palladium","Neon gas","Argon gas","Helium","Photoresists","Fluoropolymers","Advanced substrates","HBM memory","DRAM","NAND memory","Batteries","Transformers","Fiber optic components","Power semiconductors","Cooling systems","Data-center power equipment"].map((name,i)=>({name,category:i<21?"materials":"components",importance:Math.round(60+Math.random()*35),substitutionDifficulty:["Low","Medium","High"][Math.floor(Math.random()*3)],regions:["US","Taiwan","Korea","China"],exposedCompanies:companies.filter(c=>c.materials.includes(name)).map(c=>c.name),explanation:`${name} influences hardware availability, lead-time, and cost pass-through across MAG7 platforms.`,recovery:["1-2 quarters","2-4 quarters","4+ quarters"][Math.floor(Math.random()*3)]}));

const scenarios = ["Taiwan Strait disruption","China export restrictions","Advanced packaging shortage","HBM memory shortage","Lithium price shock","Copper price shock","Red Sea/Suez shipping disruption","Data-center power shortage","AI chip export control tightening","Semiconductor downturn","Rare earth export restrictions"].map((name,idx)=>({name,description:`Scenario stress test: ${name}.`,affectedCompanies:companies.map(c=>({name:c.name,score:Math.max(10,Math.min(99,c.riskScores[idx%12]+(idx%3)*4-3))})).sort((a,b)=>b.score-a.score),explanation:`${name} impacts through concentrated suppliers, material constraints, and policy/logistics chokepoints.`}));

let cache;

export async function loadData() {
  if (cache) return cache;
  let materialLedger = [];
  try {
    const res = await fetch('data/materialLedger.json');
    if (res.ok) materialLedger = await res.json();
  } catch (_e) {
    materialLedger = [];
  }

  cache = { riskFactors, companies, materials, scenarios, materialLedger };
  return cache;
}
