import { loadAllData } from './dataStore.js';
const riskFactors=["Taiwan semiconductor exposure","China manufacturing exposure","Advanced packaging exposure","HBM/memory exposure","Battery minerals exposure","Rare earth exposure","Data-center power exposure","Logistics chokepoint exposure","Single-supplier concentration","Export control exposure","Energy sensitivity","Inventory buffer weakness","Raw material concentration","Supplier financial fragility","Regulatory/political exposure"];
const byId=id=>document.getElementById(id),avg=a=>Math.round(a.reduce((x,y)=>x+y,0)/a.length);let D;
const watch=["TSMC capacity","HBM supply","CoWoS packaging","Export controls","Taiwan Strait tensions","Transformer shortages","Ocean freight rates","Port congestion","AI server lead times","Rare earth policy","Semiconductor capex cycle"];
function mode(a){return Object.entries(a.reduce((m,x)=>(m[x]=(m[x]||0)+1,m),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]||'N/A'}
function layout(t){return {title:t,paper_bgcolor:'#0f1728',plot_bgcolor:'#0f1728',font:{color:'#d7e4ff'},margin:{l:45,r:20,t:45,b:60}}}
function init(){byId('buildStamp').textContent='Build: v3.0 connected sections | '+new Date().toISOString().slice(0,10);byId('companySelect').innerHTML=D.companies.map(c=>`<option>${c.name}</option>`).join('');byId('materialSelect').innerHTML=D.materials.map(m=>`<option>${m.name}</option>`).join('');byId('scenarioSelect').innerHTML=D.scenarios.map(s=>`<option>${s.name}</option>`).join('');renderExecutiveStats();renderHeatmap();renderWatchlist();renderStrategicInsights();updateCompany(D.companies[0].name);updateAtomicExplorer(D.materials[0].name);updateScenario(D.scenarios[0].name)}
function renderExecutiveStats(){const h=[...D.companies].sort((a,b)=>avg(b.riskScores)-avg(a.riskScores))[0];const cards=[["Total companies tracked",D.companies.length],["Highest-risk company",h.name],["Most exposed sector",mode(D.companies.map(c=>c.sector))],["Biggest supplier chokepoint",mode(D.suppliers.sort((a,b)=>b.riskScore-a.riskScore).slice(0,5).map(s=>s.name))],["Most common critical material",mode(D.companies.flatMap(c=>c.materials))],["Average risk score",avg(D.companies.map(c=>avg(c.riskScores)))],["High-risk firms",D.companies.filter(c=>avg(c.riskScores)>70).length]];byId('executiveStats').innerHTML=cards.map(c=>`<div class='card'><h3>${c[0]}</h3><div class='kpi'><b>${c[1]}</b></div></div>`).join('');Plotly.newPlot('rankingChart',[{type:'bar',orientation:'h',y:D.companies.map(c=>c.name),x:D.companies.map(c=>c.riskScores[0]+c.riskScores[1]+c.riskScores[4]+c.riskScores[6]+c.riskScores[8]-c.resilienceScore),marker:{color:'#23d5ff'}}],layout('Top company risk ranking'));}
function updateCompany(name){const c=D.companies.find(x=>x.name===name);const top=riskFactors.map((f,i)=>({f,s:c.riskScores[i]})).sort((a,b)=>b.s-a.s).slice(0,3);byId('companyProfile').innerHTML=`<b>${c.name} (${c.ticker})</b> | ${c.sector}<br><b>Segments:</b> ${c.segments.join(', ')}<br><b>Products:</b> ${c.products.join(', ')}<br><b>Suppliers:</b> ${c.suppliers.join(', ')}<br><b>Materials:</b> ${c.materials.join(', ')}<br><b>Regions:</b> ${c.regions.join(', ')}<br><b>Chokepoints:</b> ${c.chokepoints.join(', ')}`;byId('ceoPanel').innerHTML=`<b>CEO Brief</b><br><b>Bottom line:</b> ${c.name} depends on concentrated physical supply chains.<br><b>Main bottleneck:</b> ${top[0].f}.<br><b>What could go wrong:</b> disruption in ${c.chokepoints[0]} / ${c.chokepoints[1]}.<br><b>Strategic move:</b> secure capacity + diversify supply.`;byId('stackFlow').innerHTML=`${c.name} → ${c.segments[0]} → ${c.products[0]} → component stack → ${c.suppliers.slice(0,3).join('/')} → ${c.regions.slice(0,3).join('/')} → ${c.materials.slice(0,4).join('/')} → ${top[0].f}`;
Plotly.newPlot('riskRadar',[{type:'scatterpolar',r:c.riskScores,theta:riskFactors,fill:'toself',line:{color:'#ff5b6e'}}],layout('Risk Radar'));Plotly.newPlot('regionalChart',[{type:'bar',x:c.regions,y:[80,74,68,62],marker:{color:'#ffb020'}}],layout('Regional Exposure'));renderNetwork(c);renderSankey(c)}
function renderNetwork(c){const edges=D.relationships.filter(r=>r.source===c.name);const nodes=[c.name,...edges.map(e=>e.target),...c.materials.slice(0,3),...c.regions.slice(0,2)];Plotly.newPlot('supplierNetwork',[{x:nodes.map((_,i)=>Math.cos(i*0.6)),y:nodes.map((_,i)=>Math.sin(i*0.6)),mode:'markers+text',text:nodes,textposition:'top center',marker:{size:nodes.map((_,i)=>i===0?28:i<=edges.length?16:11),color:nodes.map((_,i)=>i===0?'#23d5ff':i<=edges.length?'#ffb020':'#45d483')}}],layout('Supplier Network Explorer'));}
function renderSankey(c){const labels=[c.name,'Segment','Product','Supplier','Region','Material','Risk'];Plotly.newPlot('sankeyChart',[{type:'sankey',node:{label:labels,color:'#23d5ff'},link:{source:[0,1,2,3,4,5],target:[1,2,3,4,5,6],value:[10,9,8,7,6,5]}}],layout('Sankey Flow'));}
function updateAtomicExplorer(name){const m=D.materials.find(x=>x.name===name);const rows=D.ledger.filter(r=>r.material===name);byId('atomicExplorerPanel').innerHTML=`<b>${m.name}</b><br><b>Used in:</b> ${m.usedIn.join(', ')}<br><b>Exposed companies:</b> ${m.exposedCompanies.join(', ')}<br><b>Substitution:</b> ${m.substitutionDifficulty}<br><b>Disruption severity:</b> ${m.disruptionSeverity}<br><b>Why it matters:</b> ${m.strategic}`;byId('materialLedger').innerHTML='<tr><th>Company</th><th>Supplier</th><th>Origin</th><th>Route</th><th>Volume</th><th>Cost</th></tr>'+rows.map(r=>`<tr><td>${r.company}</td><td>${r.supplier}</td><td>${r.origin}</td><td>${r.route}</td><td>${r.volume_tons.toLocaleString()}</td><td>$${r.total_cost_usd_m}M</td></tr>`).join('')}
function renderHeatmap(){Plotly.newPlot('riskHeatmap',[{z:D.companies.map(c=>c.riskScores),x:riskFactors,y:D.companies.map(c=>c.name),type:'heatmap',colorscale:[[0,'#45d483'],[.5,'#ffb020'],[1,'#ff5b6e']]}],layout('Risk Heatmap'));byId('riskHeatmap').on('plotly_click',d=>{const p=d.points[0];byId('heatmapExplain').innerHTML=`<b>${p.y}</b> / <b>${p.x}</b> score ${p.z}. Trigger: dependency concentration. Mitigation: diversify suppliers, increase inventory, regional redundancy.`})}
function updateScenario(name){const s=D.scenarios.find(x=>x.name===name);const impacts=D.companies.map(c=>({name:c.name,v:Math.round((c.riskScores[0]+c.riskScores[6]+c.riskScores[7])/3)})).sort((a,b)=>b.v-a.v);byId('scenarioSimulatorPanel').innerHTML=`<b>Scenario:</b> ${s.name}<br><b>Channel:</b> ${s.description}<br><b>First-order:</b> ${s.firstOrderEffects}<br><b>Second-order:</b> ${s.secondOrderEffects}`;Plotly.newPlot('scenarioImpact',[{type:'bar',x:impacts.map(i=>i.name),y:impacts.map(i=>i.v),marker:{color:'#ff5b6e'}}],layout('Scenario Impact'));byId('scenarioExplain').innerHTML=`Most affected: ${impacts.slice(0,5).map(i=>i.name).join(', ')}. Relative beneficiaries: ${s.relativeBeneficiaries}`}
function renderWatchlist(){byId('watchlist').innerHTML=watch.map(w=>`<li>${w}</li>`).join('')}
function renderStrategicInsights(){const txt=["Platform now fully data-driven from data/*.json.","Top-25 seed model is connected to all sections.","Scenario panel now includes first-order and second-order effects.","Supplier network, Sankey, heatmap, and atomic explorer are all active."];byId('strategicInsights').innerHTML=txt.map(t=>`<li>${t}</li>`).join('');byId('whatChanged').innerHTML='<b>What changed / why it matters:</b> sections are now connected to active data and render different outcomes by company/material/scenario, making the dashboard visibly and functionally different.'}
window.addEventListener('load',async()=>{D=await loadAllData();init();byId('companySelect').addEventListener('change',e=>updateCompany(e.target.value));byId('materialSelect').addEventListener('change',e=>updateAtomicExplorer(e.target.value));byId('scenarioSelect').addEventListener('change',e=>updateScenario(e.target.value));});
