import { sharedLinkages } from './js/linkageEngine.js';
const riskFactors=["Taiwan semiconductor exposure","China manufacturing exposure","Advanced packaging exposure","HBM/memory exposure","Battery minerals exposure","Rare earth exposure","Data-center power exposure","Logistics chokepoint exposure","Single-supplier concentration","Export control exposure","Energy sensitivity","Inventory buffer weakness","Raw material concentration","Supplier financial fragility","Regulatory/political exposure"];
const byId=id=>document.getElementById(id),avg=a=>Math.round(a.reduce((x,y)=>x+y,0)/a.length);
let companies=[],materials=[],ledger=[],scenarios=[];
const watch=["TSMC capacity","HBM supply","CoWoS packaging","Taiwan Strait tension","China rare earth policy","Lithium/Nickel/Copper prices","Transformer shortages","Data-center power permits","Ocean freight rates","Port congestion","Red Sea/Suez/Panama disruptions","AI server lead times"];
const sectors=["Semiconductors","Consumer electronics","Cloud/data centers","EVs/batteries","Retail/logistics","Aerospace","Apparel","Healthcare","Industrial automation","Energy/infrastructure"];
async function loadData(){[companies,materials,ledger,scenarios]=await Promise.all([fetch('./data/companies.json').then(r=>r.json()),fetch('./data/materials.json').then(r=>r.json()),fetch('./data/materialLedger.json').then(r=>r.json()),fetch('./data/scenarios.json').then(r=>r.json())]);companies=companies.map((c,i)=>({...c,sector:["Consumer electronics","Cloud/data centers","Semiconductors","Retail/logistics","Cloud/data centers","Cloud/data centers","EVs/batteries"][i],products:["Core systems","AI infra","Device stack"],suppliers:["TSMC","Nvidia","SK Hynix","Foxconn","CATL"],regions:["Taiwan","China","US","Korea"],materials:materials.slice(0,6).map(m=>m.name),chokepoints:["Taiwan Strait","HBM","Advanced packaging","Power availability"],marketRole:["Platform OEM","Hyperscaler","Chip vendor","Integrated operator"][i%4],riskScores:c.riskScores.concat([62,58,65])}));scenarios=[...scenarios,{name:"Panama Canal disruption",channel:"Transit bottleneck",beneficiaries:"Nearshored suppliers"},{name:"Port strike",channel:"Logistics",beneficiaries:"Inventory-rich firms"},{name:"Oil price shock",channel:"Energy+freight",beneficiaries:"Efficient fleets"},{name:"Cyberattack on logistics provider",channel:"Digital logistics outage",beneficiaries:"Multi-provider shippers"}];}
function init(){byId('companySelect').innerHTML=companies.map(c=>`<option>${c.name}</option>`).join('');byId('scenarioSelect').innerHTML=scenarios.map(s=>`<option>${s.name}</option>`).join('');byId('materialSelect').innerHTML=materials.map(m=>`<option>${m.name}</option>`).join('');renderExec();renderHeatmap();renderSector();renderWatch();renderStrategic();updateCompany(companies[0].name);updateMaterial(materials[0].name);updateScenario(scenarios[0].name);}
function renderExec(){const highest=[...companies].sort((a,b)=>avg(b.riskScores)-avg(a.riskScores))[0];const commonMat=mode(companies.flatMap(c=>c.materials));const cards=[["Total companies tracked",companies.length],["Highest-risk company",highest.name],["Most exposed sector","Cloud/data centers"],["Biggest supplier chokepoint","TSMC + HBM"],["Biggest regional chokepoint","Taiwan Strait"],["Most common critical material",commonMat],["Average risk score",avg(companies.map(c=>avg(c.riskScores)))],["High-risk firms (>70)",companies.filter(c=>avg(c.riskScores)>70).length]];byId('execKpis').innerHTML=cards.map(k=>`<div class='card'><h3>${k[0]}</h3><div class='kpi'><b>${k[1]}</b></div></div>`).join('');Plotly.newPlot('rankingChart',[{type:'bar',orientation:'h',y:companies.map(c=>c.name),x:companies.map(c=>c.riskScores[0]+c.riskScores[1]+c.riskScores[4]+c.riskScores[6]+c.riskScores[8]-c.resilienceScore),marker:{color:'#23d5ff'}}],layout('Ranking: semiconductor/china/minerals/power/logistics vs resilience'));}
function updateCompany(name){const c=companies.find(x=>x.name===name);const top=riskFactors.map((f,i)=>({f,s:c.riskScores[i]})).sort((a,b)=>b.s-a.s).slice(0,4);const nar=`Why vulnerable: ${top[0].f} and ${top[1].f} are elevated. Bottleneck: ${c.chokepoints[0]} + ${c.chokepoints[1]}. Under stress: capacity delays, margin pressure, slower deployments. Risk reduction: diversify suppliers, sign long-term capacity, increase inventory buffers, regionalize final assembly.`;byId('companyProfile').innerHTML=`<b>${c.name} (${c.ticker})</b> | Sector: ${c.sector} | Market role: ${c.marketRole}<br><b>Segments:</b> ${c.segments.join(', ')}<br><b>Products/systems:</b> ${c.products.join(', ')}<br><b>Suppliers:</b> ${c.suppliers.join(', ')}<br><b>Materials:</b> ${c.materials.join(', ')}<br><b>Regions:</b> ${c.regions.join(', ')}<br><b>Chokepoints:</b> ${c.chokepoints.join(', ')}<br><b>Overall risk:</b> ${avg(c.riskScores)} | <b>Resilience:</b> ${c.resilienceScore}<br><b>Narrative:</b> ${c.chain}`;byId('ceoPanel').innerHTML=`<b>Explain like I'm the CEO</b><br><b>Bottom line:</b> ${c.name} has structural exposure to concentrated physical supply chains.<br><b>Main bottleneck:</b> ${c.chokepoints[0]} / ${c.chokepoints[1]}.<br><b>What could go wrong:</b> policy, logistics, or capacity shocks delay output.<br><b>What to monitor:</b> ${watch.slice(0,4).join(', ')}.<br><b>Strategic move:</b> dual-source critical nodes and secure long-term offtake.`;byId('stackFlow').innerHTML=`<b>Supply Chain Stack</b><br>${c.name} → ${c.segments[0]} → ${c.products[0]} → component stack → ${c.suppliers.slice(0,3).join('/')} → ${c.regions.slice(0,3).join('/')} → ${c.materials.slice(0,5).join('/')} → ${top[0].f}`;
Plotly.newPlot('riskRadar',[{type:'scatterpolar',r:c.riskScores,theta:riskFactors,fill:'toself',line:{color:'#ff5b6e'}}],layout('Risk radar'));Plotly.newPlot('regionalChart',[{type:'bar',x:c.regions,y:[88,75,62,58],marker:{color:'#ffb020'}}],layout('Regional exposure'));renderSankey(c);renderNetwork(c);}
function renderSankey(c){const labels=[c.name,'Business segment','Product/system','Supplier','Region','Material','Risk driver'];Plotly.newPlot('sankeyChart',[{type:'sankey',node:{label:labels,color:'#23d5ff'},link:{source:[0,1,2,3,4,5],target:[1,2,3,4,5,6],value:[10,9,8,7,6,5]}}],layout('Company → atomic input supply-chain flow'));}
function renderNetwork(c){const nodes=[{n:c.name,t:'company',s:28},...c.suppliers.map(s=>({n:s,t:'supplier',s:18})),...c.materials.slice(0,6).map(m=>({n:m,t:'material',s:12})),...c.regions.slice(0,3).map(r=>({n:r,t:'region',s:14})),...c.chokepoints.slice(0,2).map(k=>({n:k,t:'chokepoint',s:16}))];Plotly.newPlot('supplierNetwork',[{x:nodes.map((_,i)=>Math.cos(i*0.45)),y:nodes.map((_,i)=>Math.sin(i*0.45)),mode:'markers+text',text:nodes.map(n=>n.n),textposition:'top center',marker:{size:nodes.map(n=>n.s),symbol:nodes.map(n=>n.t==='chokepoint'?'diamond':'circle'),color:nodes.map(n=>n.t==='company'?'#23d5ff':n.t==='supplier'?'#ffb020':n.t==='material'?'#45d483':'#ff5b6e')}}],layout('Supplier network explorer'));}
function updateMaterial(name){const m=materials.find(x=>x.name===name);const rows=ledger.filter(r=>r.material===name);byId('materialInfo').innerHTML=`<b>${m.name}</b><br><b>Companies exposed:</b> ${[...new Set(rows.map(r=>r.company))].join(', ')}<br><b>Why it matters:</b> ${m.strategic}<br><b>Substitution difficulty:</b> ${m.substitution}<br><b>Disruption severity:</b> ${m.importance}/100<br><b>Time-to-recover:</b> ${m.recovery}<br><b>Strategic implication:</b> bottlenecks propagate into capacity delays and cost inflation.`;byId('materialLedger').innerHTML='<tr><th>Company</th><th>Supplier</th><th>Origin</th><th>Route</th><th>Volume</th><th>Cost</th></tr>'+rows.map(r=>`<tr><td>${r.company}</td><td>${r.supplier}</td><td>${r.origin}</td><td>${r.route}</td><td>${r.volume_tons.toLocaleString()} t</td><td>$${r.total_cost_usd_m}M</td></tr>`).join('');}
function renderHeatmap(){Plotly.newPlot('riskHeatmap',[{z:companies.map(c=>c.riskScores),x:riskFactors,y:companies.map(c=>c.name),type:'heatmap',colorscale:[[0,'#45d483'],[.5,'#ffb020'],[1,'#ff5b6e']]}],layout('Risk heatmap'));byId('riskHeatmap').on('plotly_click',d=>{const p=d.points[0];const level=p.z>75?'high':p.z>50?'medium':'low';byId('heatmapExplain').innerHTML=`<b>${p.y}</b> / <b>${p.x}</b> = ${p.z} (${level}). Trigger: concentration in suppliers/materials/chokepoints. Mitigation: diversification, inventory buffer, long-term contracts, regional redundancy.`;});}
function updateScenario(name){const s=scenarios.find(x=>x.name===name);const imp=companies.map(c=>({name:c.name,v:Math.round((c.riskScores[0]+c.riskScores[6]+c.riskScores[7])/3)})).sort((a,b)=>b.v-a.v);Plotly.newPlot('scenarioImpact',[{type:'bar',x:imp.map(i=>i.name),y:imp.map(i=>i.v),marker:{color:'#ff5b6e'}}],layout('Scenario simulator impact'));byId('scenarioExplain').innerHTML=`<b>${s.name}</b><br><b>Risk channel:</b> ${s.channel}<br><b>Most affected companies:</b> ${imp.slice(0,4).map(i=>i.name).join(', ')}<br><b>Most affected sector:</b> Cloud/data centers + semiconductors<br><b>First-order effect:</b> delivery delays and cost spikes.<br><b>Second-order effect:</b> downstream capex plans slip, demand shifts by availability.<br><b>Relative winners:</b> ${s.beneficiaries}.`;}
function renderSector(){byId('sectorView').innerHTML=sectors.map(s=>`<b>${s}</b>: common suppliers (TSMC/Nvidia/power vendors), common materials (copper/silicon/memory), common chokepoints (Taiwan/logistics/power).<br>`).join('');}
function renderWatch(){byId('watchlist').innerHTML=watch.map(w=>`<li>${w}</li>`).join('');}
function renderStrategic(){byId('strategicList').innerHTML=["Nvidia-style bottlenecks are fabrication + HBM + packaging, not demand.","Cloud firms are software-facing but physically constrained by chips, power, and cooling.","Copper, transformers, and power equipment are cross-sector bottlenecks.","Second-order risk matters: delays propagate through capex cycles and product roadmaps."].map(x=>`<li>${x}</li>`).join('');}
function mode(a){return Object.entries(a.reduce((m,x)=>(m[x]=(m[x]||0)+1,m),{})).sort((a,b)=>b[1]-a[1])[0]?.[0]||'N/A'}
function layout(title){return {title,paper_bgcolor:'#0f1728',plot_bgcolor:'#0f1728',font:{color:'#d7e4ff'},margin:{l:45,r:20,t:45,b:60}};}
window.addEventListener('load',async()=>{await loadData();init();byId('companySelect').addEventListener('change',e=>updateCompany(e.target.value));byId('materialSelect').addEventListener('change',e=>updateMaterial(e.target.value));byId('scenarioSelect').addEventListener('change',e=>updateScenario(e.target.value));});
