const riskFactors=["Taiwan semiconductor exposure","China manufacturing exposure","Advanced packaging exposure","HBM/memory exposure","Battery minerals exposure","Rare earth exposure","Data-center power exposure","Logistics chokepoint exposure","Single-supplier concentration","Export control exposure","Energy sensitivity","Inventory buffer weakness"];
const companies=[
{name:"Apple",ticker:"AAPL",riskScores:[88,85,72,64,58,66,42,69,74,61,39,55],resilienceScore:63,segments:["iPhone","Mac","Services"],products:["iPhone","Mac","Apple Silicon"],suppliers:["TSMC","Foxconn","Luxshare"],regions:["Taiwan","China","India","Vietnam"],materials:["Copper","Silicon wafers","Rare earth magnets","Batteries"],mainRiskNarrative:"Apple depends on tightly synchronized foundry, assembly, and materials chains.",strategicImplication:"Diversification helps, but concentrated nodes still dominate risk."},
{name:"Microsoft",ticker:"MSFT",riskScores:[73,32,68,81,22,28,86,48,59,72,84,52],resilienceScore:71,segments:["Azure","AI"],products:["AI data centers"],suppliers:["Nvidia","TSMC","Vertiv"],regions:["US","Taiwan","South Korea"],materials:["Copper","HBM memory","Transformers","Cooling systems"],mainRiskNarrative:"AI growth is gated by physical infrastructure, not software demand.",strategicImplication:"Power + copper + memory availability drives expansion timing."},
{name:"Nvidia",ticker:"NVDA",riskScores:[96,28,94,97,20,24,67,63,82,88,58,62],resilienceScore:56,segments:["Data Center"],products:["AI GPUs"],suppliers:["TSMC","SK Hynix","ASE"],regions:["Taiwan","South Korea"],materials:["Copper","Silicon wafers","HBM memory","Photoresists"],mainRiskNarrative:"Output is constrained by foundry-memory-packaging capacity coupling.",strategicImplication:"HBM + packaging remain hard caps on AI deployment."},
{name:"Amazon",ticker:"AMZN",riskScores:[69,54,62,79,21,24,88,77,55,66,87,49],resilienceScore:68,segments:["AWS","Retail"],products:["AI data centers","Fulfillment"],suppliers:["Nvidia","Maersk","Schneider Electric"],regions:["US","China","EU"],materials:["Copper","HBM memory","Fiber optic components","Data-center power equipment"],mainRiskNarrative:"AWS compute and global logistics are jointly exposed to physical bottlenecks.",strategicImplication:"Power and shipping disruptions can hit growth and costs together."},
{name:"Alphabet",ticker:"GOOGL",riskScores:[74,40,66,78,24,22,85,45,57,70,82,50],resilienceScore:72,segments:["Google Cloud","Devices"],products:["TPUs","AI cloud"],suppliers:["TSMC","Nvidia","Corning"],regions:["US","Taiwan","South Korea"],materials:["Copper","Silicon wafers","DRAM","Power semiconductors"],mainRiskNarrative:"Custom silicon still inherits external memory and foundry chokepoints.",strategicImplication:"Hardware procurement sophistication is strategic."},
{name:"Meta",ticker:"META",riskScores:[72,34,63,82,19,27,89,41,53,68,86,48],resilienceScore:69,segments:["AI infra"],products:["AI clusters"],suppliers:["Nvidia","Supermicro","Vertiv"],regions:["US","Taiwan"],materials:["Copper","HBM memory","Cooling systems","Data-center power equipment"],mainRiskNarrative:"Model scaling is physically tied to memory bandwidth and power conversion.",strategicImplication:"Capacity outcomes depend on hardware orchestration."},
{name:"Tesla",ticker:"TSLA",riskScores:[52,71,49,44,93,61,59,64,58,47,66,57],resilienceScore:65,segments:["EVs","Energy"],products:["EVs","Megapack"],suppliers:["CATL","Panasonic","BYD"],regions:["US","China","Germany"],materials:["Copper","Lithium","Nickel","Graphite"],mainRiskNarrative:"Mineral and battery chains dominate Tesla's cost structure volatility.",strategicImplication:"Material cycles remain the key strategic variable."}
];

const materialLedger=[
{company:"Apple",material:"Copper",supplier:"Aurubis / JX Advanced Metals (fabricators)",origin:"Chile (Escondida), Peru (Cerro Verde)",route:"Pacific shipping lanes → China/Vietnam assembly",volume_tons:185000,unit_cost_usd_ton:9350,total_cost_usd_m:1730},
{company:"Microsoft",material:"Copper",supplier:"Southwire / Prysmian / Nexans",origin:"Chile, Peru, US, Canada",route:"Bulk cathode → rod/wire mills → US data center buildouts",volume_tons:142000,unit_cost_usd_ton:9480,total_cost_usd_m:1346},
{company:"Nvidia",material:"Copper",supplier:"Mitsubishi Materials / Furukawa",origin:"Chile, Peru, DRC blended refined copper",route:"Refining Asia → substrate/PCB supply chain",volume_tons:38000,unit_cost_usd_ton:9620,total_cost_usd_m:366},
{company:"Amazon",material:"Copper",supplier:"Southwire / LS Cable",origin:"Chile, Peru, Mexico",route:"Cable & busbar supply to US/EU data centers",volume_tons:160000,unit_cost_usd_ton:9520,total_cost_usd_m:1523},
{company:"Alphabet",material:"Copper",supplier:"Prysmian / Hitachi Energy partners",origin:"Chile, Peru, Australia",route:"Grid equipment + server interconnect chain",volume_tons:133000,unit_cost_usd_ton:9490,total_cost_usd_m:1262},
{company:"Meta",material:"Copper",supplier:"Southwire / Belden ecosystem",origin:"Chile, Peru, US",route:"High-density rack power + cooling infrastructure",volume_tons:119000,unit_cost_usd_ton:9540,total_cost_usd_m:1135},
{company:"Tesla",material:"Copper",supplier:"Sumitomo / Nexans / regional mills",origin:"Chile, Peru, US",route:"Harnesses, motors, inverters, charging systems",volume_tons:275000,unit_cost_usd_ton:9380,total_cost_usd_m:2580}
];
const materials=["Copper","Silicon wafers","Lithium","Nickel","Cobalt","Graphite","Rare earth magnets","HBM memory","DRAM","NAND memory","Transformers","Cooling systems","Data-center power equipment","Fiber optic components","Photoresists"].map(m=>({name:m,exposedCompanies:companies.filter(c=>c.materials.includes(m)).map(c=>c.name),explanation:`${m} is a bottom-layer constraint that propagates into output, lead-time, and margin risk.`}));
const scenarios=["Taiwan Strait disruption","China export restrictions","Advanced packaging shortage","HBM memory shortage","Lithium price shock","Copper price shock","Red Sea/Suez shipping disruption","Data-center power shortage"].map((name,i)=>({name,description:name,affectedCompanies:companies.map(c=>({name:c.name,score:c.riskScores[i]})).sort((a,b)=>b.score-a.score)}));
const byId=id=>document.getElementById(id),avg=a=>Math.round(a.reduce((x,y)=>x+y,0)/a.length);
function init(){byId("companySelect").innerHTML=companies.map(c=>`<option>${c.name}</option>`).join('');byId("materialSelect").innerHTML=materials.map(m=>`<option>${m.name}</option>`).join('');byId("scenarioSelect").innerHTML=scenarios.map(s=>`<option>${s.name}</option>`).join('');byId("riskFilter").innerHTML=["All",...riskFactors].map(x=>`<option>${x}</option>`).join('');renderCards();renderRanking();renderHeatmap();renderStrategic();updateCompany(companies[0].name);updateMaterial('Copper');updateScenario(scenarios[0].name)}
function renderCards(){byId("companyCards").innerHTML=companies.map(c=>`<div class='card' data-name='${c.name}'><h3>${c.name}</h3><div class='kpi'><span>Overall risk</span><b>${avg(c.riskScores)}</b></div><div class='kpi'><span>Semi dependency</span><b>${c.riskScores[0]}</b></div><div class='kpi'><span>Raw material</span><b>${c.riskScores[4]}</b></div><div class='kpi'><span>Resilience</span><b>${c.resilienceScore}</b></div></div>`).join('');document.querySelectorAll('.card').forEach(el=>el.onclick=()=>{byId('companySelect').value=el.dataset.name;updateCompany(el.dataset.name)});}
function renderRanking(){Plotly.newPlot('rankingChart',[{type:'bar',orientation:'h',y:companies.map(c=>c.name),x:companies.map(c=>c.riskScores[0]+c.riskScores[4]+c.riskScores[6]-c.resilienceScore),marker:{color:'#23d5ff'}}],layout('Risk concentration ranking'));}
function updateCompany(name){const c=companies.find(x=>x.name===name);byId('companyProfile').innerHTML=`<b>${c.name}</b> (${c.ticker})<br>${c.mainRiskNarrative}<br><b>Full chain:</b> ${c.name} → ${c.segments.join('/')} → ${c.products.join('/')} → ${c.suppliers.join('/')} → ${c.regions.join('/')} → ${c.materials.join('/')} → chokepoints → ${c.strategicImplication}`;Plotly.newPlot('riskRadar',[{type:'scatterpolar',r:c.riskScores,theta:riskFactors,fill:'toself'}],layout('12-factor risk radar'));Plotly.newPlot('regionalChart',[{type:'bar',x:c.regions,y:c.regions.map((_,i)=>65+i*6),marker:{color:'#ffb020'}}],layout('Regional exposure'));renderSankey(c);renderTable(c)}
function renderSankey(c){const seq=[c.name,...c.products.slice(0,2),...c.suppliers.slice(0,2),...c.regions.slice(0,2),...c.materials.slice(0,2)];Plotly.newPlot('sankeyChart',[{type:'sankey',node:{label:seq,color:'#23d5ff'},link:{source:seq.slice(0,-1).map((_,i)=>i),target:seq.slice(1).map((_,i)=>i+1),value:seq.slice(1).map((_,i)=>10-i)}}],layout('Bottom-up chain map'));}
function renderTable(c){byId('criticalInputs').innerHTML='<tr><th>Input</th><th>Why strategic</th></tr>'+c.materials.map(m=>`<tr><td>${m}</td><td>Constrained substitute pathways and long lead-times.</td></tr>`).join('')}
function updateMaterial(name){const m=materials.find(x=>x.name===name);byId('materialInfo').innerHTML=`<b>${m.name}</b><br><b>Exposed companies:</b> ${m.exposedCompanies.join(', ')||'ecosystem wide'}<br>${m.explanation}<br><b>Note:</b> ledger values below are simulated planning estimates, not audited company disclosures.`;const rows=materialLedger.filter(r=>r.material===name);byId('materialLedger').innerHTML='<tr><th>Company</th><th>Supplier chain</th><th>Origin mines/regions</th><th>Route/chokepoint</th><th>Volume (tons/yr)</th><th>Unit cost ($/ton)</th><th>Total cost ($M/yr)</th></tr>'+rows.map(r=>`<tr><td>${r.company}</td><td>${r.supplier}</td><td>${r.origin}</td><td>${r.route}</td><td>${r.volume_tons.toLocaleString()}</td><td>${r.unit_cost_usd_ton.toLocaleString()}</td><td>${r.total_cost_usd_m.toLocaleString()}</td></tr>`).join('');}
function renderHeatmap(){Plotly.newPlot('riskHeatmap',[{z:companies.map(c=>c.riskScores),x:riskFactors,y:companies.map(c=>c.name),type:'heatmap',colorscale:[[0,'#45d483'],[.5,'#ffb020'],[1,'#ff5b6e']]}],layout('Risk heatmap'));byId('riskHeatmap').on('plotly_click',d=>{const p=d.points[0];byId('heatmapExplain').innerHTML=`<b>${p.y}</b> / <b>${p.x}</b> = <b>${p.z}</b>. Read as supplier-material-chokepoint concentration intensity.`})}
function updateScenario(name){const s=scenarios.find(x=>x.name===name),top=s.affectedCompanies;Plotly.newPlot('scenarioImpact',[{type:'bar',x:top.map(t=>t.name),y:top.map(t=>t.score),marker:{color:'#ff5b6e'}}],layout('Scenario impact'));byId('scenarioExplain').innerHTML=`<b>${s.name}</b><br>Most affected: ${top.slice(0,3).map(t=>t.name).join(', ')}`}
function renderStrategic(){byId('strategicList').innerHTML=["Decision-grade analysis needs bottom-layer material origin, route, volume, and price data.","Copper, HBM, packaging, and power equipment are shared systemic constraints across MAG7.","Use this tool as a planning framework; replace simulated values with audited procurement inputs."].map(x=>`<li>${x}</li>`).join('')}
function layout(title){return{title,font:{color:'#d7e4ff'},paper_bgcolor:'#0f1728',plot_bgcolor:'#0f1728',margin:{l:45,r:20,t:45,b:60},xaxis:{gridcolor:'#223454'},yaxis:{gridcolor:'#223454'}}}
window.addEventListener('load',()=>{init();byId('companySelect').addEventListener('change',e=>updateCompany(e.target.value));byId('materialSelect').addEventListener('change',e=>updateMaterial(e.target.value));byId('scenarioSelect').addEventListener('change',e=>updateScenario(e.target.value));});
