const riskFactors=["Taiwan semiconductor exposure","China manufacturing exposure","Advanced packaging exposure","HBM/memory exposure","Battery minerals exposure","Rare earth exposure","Data-center power exposure","Logistics chokepoint exposure","Single-supplier concentration","Export control exposure","Energy sensitivity","Inventory buffer weakness"];

const regions={"Taiwan":["Taiwan Strait"],"South Korea":["Busan Port"],"China":["South China Sea","Shanghai Port"],"US":["West Coast Ports"],"EU":["Suez/Red Sea"],"India":["Indian Ocean lanes"],"Vietnam":["South China Sea"]};
const suppliers=[
{name:"TSMC",tier:1,category:"Foundry",region:"Taiwan",components:["advanced nodes","CoWoS packaging"],dependent:["Apple","Nvidia","Microsoft","Amazon","Alphabet","Meta","Tesla"],risk:93},
{name:"SK Hynix",tier:1,category:"Memory",region:"South Korea",components:["HBM","DRAM"],dependent:["Nvidia","Microsoft","Amazon","Alphabet","Meta"],risk:88},
{name:"Samsung",tier:1,category:"Memory/Displays",region:"South Korea",components:["HBM","Displays","NAND"],dependent:["Apple","Nvidia"],risk:79},
{name:"Foxconn",tier:1,category:"Assembly",region:"China",components:["iPhone assembly","server racks"],dependent:["Apple","Amazon"],risk:76},
{name:"ASE",tier:2,category:"Packaging",region:"Taiwan",components:["Advanced packaging"],dependent:["Nvidia","Apple"],risk:82},
{name:"Amkor",tier:2,category:"Packaging",region:"Southeast Asia",components:["OSAT"],dependent:["Nvidia","Apple"],risk:74},
{name:"CATL",tier:1,category:"Battery",region:"China",components:["LFP cells"],dependent:["Tesla"],risk:81},
{name:"Schneider Electric",tier:1,category:"Power",region:"EU",components:["UPS/switchgear"],dependent:["Microsoft","Amazon","Alphabet","Meta"],risk:69},
{name:"Vertiv",tier:1,category:"Cooling/Power",region:"US",components:["Cooling","Power distribution"],dependent:["Microsoft","Amazon","Alphabet","Meta"],risk:72}
];

const companies=[
{ticker:"AAPL",name:"Apple",sector:"Consumer Tech",segments:["iPhone","Mac","Services"],products:["iPhone","Mac","iPad","Apple Silicon"],suppliers:["TSMC","Foxconn","Pegatron","Luxshare","Samsung","ASE"],materials:["Silicon wafers","Copper","Rare earth magnets","Batteries","Cobalt","Lithium","Gold","Photoresists"],regions:["Taiwan","China","India","Vietnam"],riskScores:[88,85,72,64,58,66,42,69,74,61,39,55],resilienceScore:63,mainRiskNarrative:"Apple’s risk stack runs top-to-bottom: product demand depends on TSMC wafers, assembly clusters, precision components, and shipping corridors.",strategicImplication:"Resilience improves with India/Vietnam ramp but Taiwan-node concentration remains structural."},
{ticker:"MSFT",name:"Microsoft",sector:"Cloud & Software",segments:["Azure","Office","AI"],products:["Azure AI","Data centers","Surface"],suppliers:["Nvidia","TSMC","SK Hynix","Dell","Supermicro","Schneider Electric","Vertiv"],materials:["HBM memory","DRAM","Copper","Transformers","Cooling systems","Data-center power equipment","Fiber optic components"],regions:["US","Taiwan","South Korea","EU"],riskScores:[73,32,68,81,22,28,86,48,59,72,84,52],resilienceScore:71,mainRiskNarrative:"Azure AI growth is physically gated by GPU supply, HBM, racks, cooling, and regional grid approvals.",strategicImplication:"Software margins increasingly hinge on power and hardware lead-times."},
{ticker:"NVDA",name:"Nvidia",sector:"Semiconductors",segments:["Data center","Gaming","Automotive"],products:["AI GPUs","Networking","Grace CPUs"],suppliers:["TSMC","SK Hynix","Samsung","Micron","ASE","Amkor"],materials:["Silicon wafers","HBM memory","Neon gas","Photoresists","Advanced substrates","Copper","Gold","Argon gas"],regions:["Taiwan","South Korea","US","Malaysia"],riskScores:[96,28,94,97,20,24,67,63,82,88,58,62],resilienceScore:56,mainRiskNarrative:"Nvidia demand is strong, but output depends on foundry nodes + HBM + advanced packaging synchronization.",strategicImplication:"Physical bottlenecks can cap AI deployment regardless of software demand."},
{ticker:"AMZN",name:"Amazon",sector:"E-commerce & Cloud",segments:["AWS","Retail","Logistics"],products:["AWS AI","Fulfillment","Kuiper"],suppliers:["Nvidia","TSMC","Arista","Vertiv","Maersk","UPS","Schneider Electric"],materials:["HBM memory","Copper","Fiber optic components","Cooling systems","Data-center power equipment","Transformers"],regions:["US","China","Taiwan","EU"],riskScores:[69,54,62,79,21,24,88,77,55,66,87,49],resilienceScore:68,mainRiskNarrative:"Amazon combines AI infrastructure risk with global logistics throughput risk.",strategicImplication:"Dual shocks (shipping + power) can hit both AWS growth and retail efficiency."},
{ticker:"GOOGL",name:"Alphabet",sector:"Internet & Cloud",segments:["Google Cloud","Ads","Devices"],products:["TPUs","AI cloud","Pixel"],suppliers:["TSMC","Nvidia","Broadcom","SK Hynix","Corning","Vertiv"],materials:["Silicon wafers","HBM memory","DRAM","Copper","Power semiconductors","Data-center power equipment"],regions:["US","Taiwan","South Korea"],riskScores:[74,40,66,78,24,22,85,45,57,70,82,50],resilienceScore:72,mainRiskNarrative:"Alphabet’s AI stack ties custom silicon plans to the same constrained advanced supply base.",strategicImplication:"TPU strategy still inherits foundry, memory, and power chokepoints."},
{ticker:"META",name:"Meta",sector:"Social & AI",segments:["Family of apps","Reality Labs","AI infra"],products:["AI clusters","Recommenders","XR devices"],suppliers:["Nvidia","TSMC","Supermicro","Arista","Vertiv","Schneider Electric"],materials:["HBM memory","Copper","Cooling systems","Data-center power equipment","Rare earth magnets","Fiber optic components"],regions:["US","Taiwan","South Korea"],riskScores:[72,34,63,82,19,27,89,41,53,68,86,48],resilienceScore:69,mainRiskNarrative:"Meta’s model ambition maps directly to rack density, memory bandwidth, and power conversion capacity.",strategicImplication:"Compute race is won by procurement orchestration, not just algorithms."},
{ticker:"TSLA",name:"Tesla",sector:"EV & Energy",segments:["EVs","Energy storage","Autonomy"],products:["Model lineup","Megapack","Dojo"],suppliers:["Panasonic","CATL","LG Energy Solution","BYD","TSMC","Murata"],materials:["Lithium","Nickel","Cobalt","Graphite","Copper","Aluminum","Power semiconductors","Rare earth magnets"],regions:["US","China","Germany"],riskScores:[52,71,49,44,93,61,59,64,58,47,66,57],resilienceScore:65,mainRiskNarrative:"Tesla’s chain is clear: minerals → cathode/anode/cells → pack integration → power electronics → final vehicle/energy systems.",strategicImplication:"Raw-material cycles and regional policy remain the core volatility sources."}
];

const materialCatalog=["Silicon wafers","Copper","Aluminum","Lithium","Nickel","Cobalt","Graphite","Rare earth magnets","Gallium","Germanium","Tantalum","Tin","Gold","Silver","Palladium","Neon gas","Argon gas","Helium","Photoresists","Fluoropolymers","Advanced substrates","HBM memory","DRAM","NAND memory","Batteries","Transformers","Fiber optic components","Power semiconductors","Cooling systems","Data-center power equipment"];const materials=materialCatalog.map((name,i)=>({name,category:i<21?"Raw/chemical":"System input",importance:65+(i%5)*7,substitutionDifficulty:["Low","Medium","High"][i%3],regions:Object.keys(regions).slice(i%4,i%4+3),exposedCompanies:companies.filter(c=>c.materials.includes(name)).map(c=>c.name),explanation:`${name} sits in the bottom-layer of production physics and lead-time control.`,recovery:["1-2 quarters","2-4 quarters","4+ quarters"][i%3],strategic:`Disruption in ${name} propagates upward into output, cost, and strategic timing.`}));

const scenarios=[
{name:"Taiwan Strait disruption",description:"Shock to foundry + packaging + electronics corridors.",riskChannel:"TSMC fabrication and OSAT concentration",winners:"Firms with inventory buffers and non-Taiwan optionality"},
{name:"China export restrictions",description:"Materials/components export friction and assembly stress.",riskChannel:"Assembly + battery + specialty materials",winners:"Companies with India/US/EU diversification"},
{name:"Advanced packaging shortage",description:"CoWoS/OSAT bottlenecks extend AI server delivery.",riskChannel:"Packaging capacity",winners:"Vendors with pre-booked capacity"},
{name:"HBM memory shortage",description:"AI GPU system bottleneck through memory stack scarcity.",riskChannel:"SK Hynix/Samsung/Micron",winners:"Lower-memory-optimized model operators"},
{name:"Lithium price shock",description:"Battery cost pressure wave",riskChannel:"Cathode economics",winners:"Recycling and LFP-heavy strategies"},
{name:"Copper price shock",description:"Grid + cabling + cooling capex increases",riskChannel:"Power and interconnect inflation",winners:"Efficiency-first designs"},
{name:"Red Sea/Suez shipping disruption",description:"Transit-time spike for EU-Asia flows",riskChannel:"Shipping lanes",winners:"Airfreight-ready and nearshored networks"},
{name:"Data-center power shortage",description:"AI capacity delayed by utility interconnect constraints",riskChannel:"Grid and transformer bottlenecks",winners:"Power-contracted incumbents"},
{name:"AI chip export control tightening",description:"Policy-driven demand routing changes",riskChannel:"Export controls",winners:"Domestic-compliance supply chains"},
{name:"Semiconductor downturn",description:"Inventory correction and utilization swings",riskChannel:"Capex reset",winners:"Cash-rich buyers locking favorable terms"},
{name:"Rare earth export restrictions",description:"Motor/magnet input stress",riskChannel:"NdFeB and refining concentration",winners:"Magnet-light redesign strategies"}
].map((s,idx)=>({...s,affectedCompanies:companies.map(c=>({name:c.name,score:Math.max(10,Math.min(99,c.riskScores[idx%12]+(idx%4)*3))})).sort((a,b)=>b.score-a.score)}));

const sankeyFlows={Nvidia:["Nvidia","AI GPUs","TSMC fabrication","Taiwan","Silicon wafers","Photoresists","HBM memory","SK Hynix","Advanced packaging","ASE/Amkor"],Apple:["Apple","iPhone/Mac","Foxconn/Luxshare","China/India/Vietnam","Batteries","Rare earth magnets","Apple Silicon","TSMC","Taiwan Strait"],Tesla:["Tesla","EVs/Megapack","Battery cells","CATL/LG/Panasonic","Lithium/Nickel/Graphite","Power semiconductors","Factories","US/China/Germany","Policy/logistics"]};

const byId=id=>document.getElementById(id); const avg=a=>Math.round(a.reduce((x,y)=>x+y,0)/a.length);
function init(){
  byId("companySelect").innerHTML=companies.map(c=>`<option>${c.name}</option>`).join("");
  byId("materialSelect").innerHTML=materials.map(m=>`<option>${m.name}</option>`).join("");
  byId("scenarioSelect").innerHTML=scenarios.map(s=>`<option>${s.name}</option>`).join("");
  byId("riskFilter").innerHTML=["All",...riskFactors].map(x=>`<option>${x}</option>`).join("");
  renderCards();renderRanking();renderHeatmap();renderStrategic();updateCompany(companies[0].name);updateMaterial(materials[0].name);updateScenario(scenarios[0].name);
}
function renderCards(){byId("companyCards").innerHTML=companies.map(c=>`<div class='card' data-name='${c.name}'><h3>${c.name} <span class='risk-${c.resilienceScore>68?"low":"high"}'>Resilience ${c.resilienceScore}</span></h3>${[["Overall risk",avg(c.riskScores)],["Semiconductor dependency",c.riskScores[0]],["China/Taiwan exposure",Math.round((c.riskScores[0]+c.riskScores[1])/2)],["AI infrastructure dependency",c.riskScores[3]],["Energy/DC dependency",c.riskScores[6]],["Raw material exposure",c.riskScores[4]],["Logistics chokepoints",c.riskScores[7]]].map(x=>`<div class='kpi'><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</div>`).join("");document.querySelectorAll('.card').forEach(el=>el.onclick=()=>{byId('companySelect').value=el.dataset.name;updateCompany(el.dataset.name)});}
function renderRanking(){const metrics=[0,1,4,6];const x=companies.map(c=>metrics.reduce((s,m)=>s+c.riskScores[m],0)-c.resilienceScore);Plotly.newPlot('rankingChart',[{type:'bar',orientation:'h',y:companies.map(c=>c.name),x,marker:{color:'#23d5ff'}}],layout('Ranking: highest concentrated risk stack'));}
function updateCompany(name){const c=companies.find(x=>x.name===name);byId('companyProfile').innerHTML=`<b>${c.name} (${c.ticker})</b> · ${c.sector}<br><b>Main supply-chain story:</b> ${c.mainRiskNarrative}<br><b>Top-to-bottom chain:</b> ${c.name} → ${c.segments.join('/')} → ${c.products.slice(0,2).join('/')} → components → ${c.suppliers.slice(0,4).join('/')} → ${c.regions.join('/')} → ${c.materials.slice(0,6).join('/')} → chokepoints → strategic outcomes.<br><b>Strategic implication:</b> ${c.strategicImplication}`;
 Plotly.newPlot('riskRadar',[{type:'scatterpolar',r:c.riskScores,theta:riskFactors,fill:'toself',line:{color:'#ff5b6e'}}],layout('Full risk radar (12 factors)'));
 Plotly.newPlot('regionalChart',[{type:'bar',x:c.regions,y:c.regions.map(r=>70+(regions[r]?.length||1)*8),marker:{color:'#ffb020'},text:c.regions.map(r=>(regions[r]||[]).join(', ')),hovertemplate:'%{x}<br>Chokepoints: %{text}<extra></extra>'}],layout('Regional exposure + chokepoints'));
 renderSankey(c);renderNetwork(c);renderTable(c);
}
function renderSankey(c){const seq=sankeyFlows[c.name]||[c.name,...c.products.slice(0,2),...c.suppliers.slice(0,2),...c.regions.slice(0,2),...c.materials.slice(0,2)];const source=seq.slice(0,-1).map((_,i)=>i);const target=seq.slice(1).map((_,i)=>i+1);const value=source.map(i=>Math.max(2,12-i));Plotly.newPlot('sankeyChart',[{type:'sankey',node:{label:seq,color:'#23d5ff'},link:{source,target,value,color:'rgba(255,176,32,.4)'}}],layout('Company → inputs → chokepoints flow'));}
function renderNetwork(c){const sup=suppliers.filter(s=>c.suppliers.includes(s.name));const mat=materials.filter(m=>c.materials.includes(m.name)).slice(0,8);const nodes=[...companies.map(x=>({name:x.name,t:'company',imp:24})),...sup.map(s=>({name:s.name,t:'supplier',imp:12+s.risk/10})),...mat.map(m=>({name:m.name,t:'material',imp:10+m.importance/12}))];Plotly.newPlot('supplierNetwork',[{x:nodes.map((_,i)=>Math.cos(i*0.5)),y:nodes.map((_,i)=>Math.sin(i*0.5)),mode:'markers+text',text:nodes.map(n=>n.name),textposition:'top center',customdata:nodes.map(n=>n.t),hovertemplate:'%{text}<br>Type: %{customdata}<extra></extra>',marker:{size:nodes.map(n=>n.imp),color:nodes.map(n=>n.t==='company'?'#23d5ff':n.t==='supplier'?'#ff5b6e':'#45d483')}}],layout('Supplier network explorer (click for exposure)'));}
function renderTable(c){byId('criticalInputs').innerHTML="<tr><th>Critical Input</th><th>Why it matters</th><th>Substitution</th><th>Recover</th></tr>"+materials.filter(m=>c.materials.includes(m.name)).map(m=>`<tr><td>${m.name}</td><td>${m.explanation}</td><td>${m.substitutionDifficulty}</td><td>${m.recovery}</td></tr>`).join('');}
function updateMaterial(name){const m=materials.find(x=>x.name===name);byId('materialInfo').innerHTML=`<b>${m.name}</b><br><b>Companies exposed:</b> ${m.exposedCompanies.join(', ')||'Indirect ecosystem-wide'}<br><b>Why it matters:</b> ${m.explanation}<br><b>Key regions:</b> ${m.regions.join(', ')}<br><b>Substitution difficulty:</b> ${m.substitutionDifficulty}<br><b>Disruption impact:</b> ${m.importance}/100<br><b>Time-to-recover:</b> ${m.recovery}<br><b>Strategic implication:</b> ${m.strategic}`;}
function renderHeatmap(){Plotly.newPlot('riskHeatmap',[{z:companies.map(c=>c.riskScores),x:riskFactors,y:companies.map(c=>c.name),type:'heatmap',colorscale:[[0,'#45d483'],[0.5,'#ffb020'],[1,'#ff5b6e']]}],layout('Cross-company risk heatmap'));byId('riskHeatmap').on('plotly_click',d=>{const p=d.points[0];const company=companies.find(c=>c.name===p.y);byId('heatmapExplain').innerHTML=`<b>${p.y}</b> · <b>${p.x}</b> score: <b>${p.z}</b><br>Bottom-layer interpretation: this risk reflects supplier/material/chokepoint concentration.<br><b>Narrative:</b> ${company.mainRiskNarrative}`;});}
function updateScenario(name){const s=scenarios.find(x=>x.name===name);const top=s.affectedCompanies.slice(0,7);Plotly.newPlot('scenarioImpact',[{type:'bar',x:top.map(t=>t.name),y:top.map(t=>t.score),marker:{color:'#ff5b6e'}}],layout('Scenario severity by company'));byId('scenarioExplain').innerHTML=`<b>${s.name}</b><br>${s.description}<br><b>Risk channel:</b> ${s.riskChannel}<br><b>Most affected:</b> ${top.slice(0,4).map(t=>`${t.name} (${t.score})`).join(', ')}<br><b>Possible winners:</b> ${s.winners}`;}
function renderStrategic(){byId('strategicList').innerHTML=["Nvidia is the highest exposure name for advanced semiconductor bottlenecks (HBM + packaging + foundry concentration).","Apple remains exposed to Asian manufacturing concentration despite diversification gains.","Tesla has the most explicit minerals-to-output chain (lithium, nickel, graphite, cobalt, copper).","Cloud hyperscalers are physically dependent on GPU stacks, memory, transformers, cooling, and power equipment.","AI growth is constrained by physical infrastructure, not just software capability.","Core chokepoints: TSMC, HBM suppliers, packaging lines, power interconnects, transformers, shipping corridors."].map(x=>`<li>${x}</li>`).join('');}
function layout(title){return{title,font:{color:'#d7e4ff'},paper_bgcolor:'#0f1728',plot_bgcolor:'#0f1728',margin:{l:45,r:20,t:45,b:65},xaxis:{gridcolor:'#223454',tickangle:-20},yaxis:{gridcolor:'#223454'}}}
window.addEventListener('load',()=>{init();byId('companySelect').addEventListener('change',e=>updateCompany(e.target.value));byId('materialSelect').addEventListener('change',e=>updateMaterial(e.target.value));byId('scenarioSelect').addEventListener('change',e=>updateScenario(e.target.value));});
